Events:Subscribe('Level:LoadingInfo', function(screenInfo)
	if screenInfo == "Running" or screenInfo == "Blocking on shader creation" or screenInfo == "Loading done" then
	if Config.consolespam then
		print("*** Tablesetup Vehicles loaded ***");
	end
	end
end)

vehicleTable = {
	-- Air Vehicles
	["A10_THUNDERBOLT"] = "A-10 THUNDERBOLT",
	["A10_THUNDERBOLT_spjet"] = "A-10 THUNDERBOLT",
	["Ka-60"] = "KA-60 KASATKA",
	["AC130"] = "GUNSHIP",
	["C130"] = "GUNSHIP",
	["AGM-144_Hellfire_TV"] = "TV MISSILE",
	["F35B"] = "F-35",
	["Mi28"] = "MI-28 HAVOC",
	["Su37"] = "SU-37",
	["Su-35BM Flanker-E"] = "SU-35BM FLANKER-E",
	["Su-25TM"] = "SU-25TM FROGFOOT",
	["AH1Z"] = "AH-1Z VIPER",
	["AH1Z_coop"] = "AH-1Z VIPER",
	["AH6_Littlebird"] = "AH-6J LITTLE BIRD",
	["AH6_Littlebird_EQ"] = "AH-6J LITTLE BIRD",
	["F16"] = "F/A-18E SUPER HORNET",
	["F18_Wingman"] = "F/A-18E SUPER HORNET",
	["Venom"] = "UH-1Y VENOM",
	["Venom_coop"] = "UH-1Y VENOM",
	["Wz11_SP_Paris"] = "Z-11W",
	["Z-11w"] = "Z-11W",

	-- Land Vehicles
	["EODBot"] = "EOD BOT",
	["M224"] = "M224 MORTAR",
	--
	["9K22_Tunguska_M"] = "9K22 TUNGUSKA-M",
	["9K22_Tunguska_M_AI"] = "9K22 TUNGUSKA-M",
	["Kornet"] = "9M133 KORNET LAUNCHER",
	["AAV-7A1"] = "AAV-7A1 AMTRAC",
	["VodnikModified_V2"] = "BARSUK",
	["STAR_1466"] = "BM-23",
	["BMP2"] = "BMP-2M",
	["BMP2_SP007"] = "BMP-2M",
	["BTR90"] = "BTR-90",
	["Centurion_C-RAM"] = "CENTURION C-RAM",
	["Centurion_C-RAM_Carrier"] = "CENTURION C-RAM",
	["CivilianCar_03_Vehicle"] = "CIVILIAN CAR",
	["CivilianCar_03_Vehicle_SPJet"] = "CIVILIAN CAR",
	["DeliveryVan_Vehicle"] = "DELIVERY VAN",
	["KLR650"] = "DIRTBIKE",
	["DPV"] = "DPV",
	["GAZ-3937_Vodnik"] = "GAZ-3937 VODNIK",
	["GrowlerITV"] = "GROWLER ITV",
	["GrowlerITV_Valley"] = "GROWLER ITV",
	["Humvee_ASRAD"] = "HMMWV ASRAD",
	["LAV25"] = "LAV-25",
	["LAV25_AI"] = "LAV-25",
	["LAV25_Paradrop"] = "LAV-25",
	["LAV_AD"] = "LAV-AD",
	["M1Abrams"] = "M1 ABRAMS",
	["M1Abrams_AI_SP007"] = "M1 ABRAMS",
	["M1Abrams_SP007"] = "M1 ABRAMS",
	["M1Abrams_SP_Rail"] = "M1 ABRAMS",
	["Humvee"] = "M1114 HMMWV",
	["HumveeArmored"] = "M1114 HMMWV",
	["HumveeArmored_hmg"] = "M1114 HMMWV",
	["M1128-Stryker"] = "M1128",
	["HIMARS"] = "M142",
	["TOW2"] = "M220 TOW LAUNCHER",
	["Pantsir-S1"] = "PANTSIR-S1",
	["HumveeModified"] = "PHOENIX",
	["PoliceVan_Vehicle"] = "POLICE VAN",
	["QuadBike"] = "QUAD BIKE",
	["RHIB"] = "RHIB BOAT",
	["VanModified"] = "RHINO",
	["SkidLoader"] = "SKID LOADER",
	["2S25_SPRUT-SD"] = "SPRUT-SD",
	["Paris_SUV"] = "SUV",
	["Paris_SUV_Coop"] = "SUV",
	["Sniper_SUV"] = "SUV",
	["Villa_SUV"] = "SUV",
	["T90"] = "T-90A",
	["T90_SP007"] = "T-90A",
	["T90_T55_SP007"] = "T-90A",
	["TechnicalTruck"] = "TECHNICAL TRUCK",
	["TechnicalTruck_Restricted"] = "TECHNICAL TRUCK",
	["VDV Buggy"] = "VDV Buggy",
	["VodnikPhoenix"] = "VODNIK AA"
}
